# Generated by Django 5.2.7 on 2025-10-13 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0002_alter_usuario_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cancion',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radioapp.autor'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PersonaDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferida', models.BooleanField(default=False)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.direccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('autores', models.ManyToManyField(to='radioapp.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Reproducciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.cancion')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.podcast')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radioapp.usuario')),
            ],
        ),
    ]
