# Generated by Django 5.2.7 on 2025-10-15 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0003_remove_usuario_direccion_cancion_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='tematica',
            field=models.CharField(blank=True, choices=[('Actualidad', 'Actualidad'), ('Investigacion', 'Investigacion'), ('Terror', 'Terror')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reproducciones',
            name='cancion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radioapp.cancion'),
        ),
        migrations.AlterField(
            model_name='reproducciones',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radioapp.podcast'),
        ),
    ]
