# Generated by Django 5.2.7 on 2025-10-16 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radioapp', '0004_podcast_tematica_alter_reproducciones_cancion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'Canción', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='personadireccion',
            options={'verbose_name': 'Persona Dirección', 'verbose_name_plural': 'Persona Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'verbose_name': 'Podcast', 'verbose_name_plural': 'Podcasts'},
        ),
        migrations.AlterModelOptions(
            name='reproducciones',
            options={'verbose_name': 'Reproducción', 'verbose_name_plural': 'Reproducciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='personadireccion',
            unique_together={('direccion', 'usuario')},
        ),
    ]
