# Generated by Django 5.2.7 on 2025-10-02 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0004_tarea_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSprint', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='programador',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programador',
            name='rol',
            field=models.CharField(choices=[('PR', 'Programador'), ('TE', 'Tester'), ('JP', 'Jefe de proyecto')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='tarea',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='scrum.sprint'),
        ),
    ]
