# Generated by Django 5.2.7 on 2025-10-06 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrum', '0007_remove_tarea_usuario_tarea_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
